name: run test after every push
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.5
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.5

    - name: Make tests.sh executable
      run: chmod +x ./project/tests.sh
    
    - name: Test with test-files
      run: |
        ./project/tests.sh
